<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Shoe catalog. Images are public SVG placeholders under /images/placeholders (served by Laravel).
     * Uploads still use storage paths (products/...) after admin file upload.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Air Velocity Pro — Road Runner',
                'description' => 'Lightweight mesh upper with responsive foam midsole. Built for tempo days and long mileage. Breathable, secure lockdown, and a grippy rubber outsole for wet pavement.',
                'price' => 189.99,
                'brand' => 'Nike',
                'category' => 'Running',
                'size' => json_encode(['7', '7.5', '8', '8.5', '9', '9.5', '10', '11']),
                'color' => 'Crimson / Black',
                'material' => 'Engineered mesh, synthetic overlays',
                'sole_type' => 'Rubber outsole, cushioned EVA midsole',
                'stock_quantity' => 42,
                'status' => 'active',
            ],
            [
                'name' => 'Pulse Trainer 360',
                'description' => 'Versatile gym-to-street sneaker with a stable heel clip and flexible forefoot. Ideal for HIIT, short runs, and everyday wear.',
                'price' => 129.99,
                'brand' => 'Adidas',
                'category' => 'Sneakers',
                'size' => json_encode(['7', '8', '9', '10', '11', '12']),
                'color' => 'White / Grey',
                'material' => 'Knit textile upper',
                'sole_type' => 'Non-marking rubber, Boost-style foam',
                'stock_quantity' => 55,
                'status' => 'active',
            ],
            [
                'name' => 'Summit Trail GTX',
                'description' => 'Water-resistant boot with aggressive lug pattern and ankle support. Tackle gravel, mud, and light hikes with confidence.',
                'price' => 219.00,
                'brand' => 'ASICS',
                'category' => 'Boots',
                'size' => json_encode(['8', '8.5', '9', '9.5', '10', '10.5', '11']),
                'color' => 'Olive / Black',
                'material' => 'Synthetic leather, Gore-Tex style lining',
                'sole_type' => 'Vibram-style lug rubber',
                'stock_quantity' => 28,
                'status' => 'active',
            ],
            [
                'name' => 'City Drift Canvas',
                'description' => 'Low-profile casual shoe with a cushioned insole and classic silhouette. Pair with denim or joggers for an easy weekend look.',
                'price' => 79.50,
                'brand' => 'StrideLab',
                'category' => 'Casual',
                'size' => json_encode(['6', '7', '8', '9', '10', '11', '12']),
                'color' => 'Navy',
                'material' => 'Canvas upper, textile lining',
                'sole_type' => 'Cupsole rubber',
                'stock_quantity' => 80,
                'status' => 'active',
            ],
            [
                'name' => 'FuelCell Prism',
                'description' => 'Snappy plate-assisted ride for interval training. Streamlined upper reduces weight without sacrificing structure.',
                'price' => 165.00,
                'brand' => 'New Balance',
                'category' => 'Running',
                'size' => json_encode(['7.5', '8', '8.5', '9', '9.5', '10']),
                'color' => 'Neon Lime',
                'material' => 'Mono mesh, TPU heel',
                'sole_type' => 'Carbon-infused plate, blown rubber',
                'stock_quantity' => 33,
                'status' => 'active',
            ],
            [
                'name' => 'Court Classic Low',
                'description' => 'Heritage court silhouette with premium leather-look panels and a durable cupsole. Timeless style for campus and city.',
                'price' => 94.99,
                'brand' => 'Adidas',
                'category' => 'Sneakers',
                'size' => json_encode(['6', '7', '8', '9', '10', '11']),
                'color' => 'Cloud White',
                'material' => 'Synthetic leather',
                'sole_type' => 'Herringbone rubber cupsole',
                'stock_quantity' => 60,
                'status' => 'active',
            ],
            [
                'name' => 'Arctic Grip Winter Boot',
                'description' => 'Insulated boot with deep tread for snow and slush. Thermal lining keeps feet warm without bulk.',
                'price' => 199.99,
                'brand' => 'StrideLab',
                'category' => 'Boots',
                'size' => json_encode(['8', '9', '10', '11', '12']),
                'color' => 'Charcoal',
                'material' => 'Nubuck-style synthetic, fleece lining',
                'sole_type' => 'Ice-grip rubber compound',
                'stock_quantity' => 22,
                'status' => 'active',
            ],
            [
                'name' => 'Slipstream Retro',
                'description' => 'Chunky 90s-inspired sneaker with bold color blocking. Soft collar padding and a wide platform for all-day comfort.',
                'price' => 110.00,
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'size' => json_encode(['7', '8', '9', '10', '11']),
                'color' => 'Royal / White',
                'material' => 'Leather & mesh mix',
                'sole_type' => 'Foam wedge, rubber pods',
                'stock_quantity' => 47,
                'status' => 'active',
            ],
            [
                'name' => 'Recovery Slide Max',
                'description' => 'Post-run recovery slide with contoured footbed and cloud foam. Not for sport—pure comfort after the miles.',
                'price' => 45.00,
                'brand' => 'StrideLab',
                'category' => 'Casual',
                'size' => json_encode(['6', '7', '8', '9', '10', '11', '12']),
                'color' => 'Black',
                'material' => 'EVA one-piece upper',
                'sole_type' => 'Textured EVA outsole',
                'stock_quantity' => 120,
                'status' => 'active',
            ],
            [
                'name' => 'Velocity Tempo 5K',
                'description' => 'Racing-flat feel for 5K–10K efforts. Minimal upper, fast turnover, and a secure toe box.',
                'price' => 139.00,
                'brand' => 'ASICS',
                'category' => 'Running',
                'size' => json_encode(['7', '7.5', '8', '8.5', '9', '10']),
                'color' => 'Electric Blue',
                'material' => 'Ultra-light mesh',
                'sole_type' => 'Racing rubber, thin midsole',
                'stock_quantity' => 30,
                'status' => 'active',
            ],
            [
                'name' => 'Heritage Moc Toe',
                'description' => 'Workwear-inspired casual boot with contrast stitching and a cushy wedge sole. Dress up or down.',
                'price' => 175.00,
                'brand' => 'New Balance',
                'category' => 'Boots',
                'size' => json_encode(['8', '8.5', '9', '9.5', '10', '11']),
                'color' => 'Tan',
                'material' => 'Oiled leather-look synthetic',
                'sole_type' => 'Crepe-style rubber wedge',
                'stock_quantity' => 25,
                'status' => 'active',
            ],
            [
                'name' => 'LiteStride Walker',
                'description' => 'Walking shoe with plush insole and wide toe box. Great for commutes and long shifts on your feet.',
                'price' => 99.00,
                'brand' => 'StrideLab',
                'category' => 'Casual',
                'size' => json_encode(['7', '8', '9', '10', '11', '12', '13']),
                'color' => 'Stone',
                'material' => 'Breathable knit',
                'sole_type' => 'Flexible rubber, EVA core',
                'stock_quantity' => 70,
                'status' => 'active',
            ],
            [
                'name' => 'Zoom Court Elite',
                'description' => 'Indoor court grip with lateral support for quick cuts. Low-profile cushioning keeps you connected to the floor.',
                'price' => 119.99,
                'brand' => 'Nike',
                'category' => 'Sneakers',
                'size' => json_encode(['7', '8', '9', '10', '11', '12']),
                'color' => 'Black / Volt',
                'material' => 'Synthetic leather cage',
                'sole_type' => 'Gum rubber herringbone',
                'stock_quantity' => 38,
                'status' => 'active',
            ],
            [
                'name' => 'DuraHike Mid',
                'description' => 'Mid-cut hiking boot with toe bumper and padded collar. Supportive shank for uneven terrain.',
                'price' => 209.00,
                'brand' => 'ASICS',
                'category' => 'Boots',
                'size' => json_encode(['8', '9', '10', '11']),
                'color' => 'Brown / Green',
                'material' => 'Suede-style & ripstop',
                'sole_type' => 'Multi-directional lug rubber',
                'stock_quantity' => 19,
                'status' => 'active',
            ],
            [
                'name' => 'Cloudfoam Daily',
                'description' => 'Soft step-in comfort with a sock-like fit. Your go-to for errands and travel days.',
                'price' => 85.00,
                'brand' => 'Adidas',
                'category' => 'Casual',
                'size' => json_encode(['6', '7', '8', '9', '10', '11']),
                'color' => 'Grey Two',
                'material' => 'Primeknit-style textile',
                'sole_type' => 'Cloudfoam EVA',
                'stock_quantity' => 64,
                'status' => 'active',
            ],
            [
                'name' => 'Marathon Elite Carbon',
                'description' => 'Full-length carbon plate and max-stack foam for race day. Engineered for PB chasers who want propulsion and protection.',
                'price' => 249.00,
                'brand' => 'New Balance',
                'category' => 'Running',
                'size' => json_encode(['7', '7.5', '8', '8.5', '9', '9.5', '10']),
                'color' => 'Black / Pink',
                'material' => 'Race mesh, minimal overlays',
                'sole_type' => 'Carbon plate, high-stack foam',
                'stock_quantity' => 18,
                'status' => 'active',
            ],
        ];

        $placeholderByCategory = [
            'Running' => '/images/placeholders/shoe-running.svg',
            'Sneakers' => '/images/placeholders/shoe-sneakers.svg',
            'Casual' => '/images/placeholders/shoe-casual.svg',
            'Boots' => '/images/placeholders/shoe-boots.svg',
        ];

        foreach ($products as $row) {
            $row['image'] = $placeholderByCategory[$row['category']] ?? '/images/placeholders/shoe-running.svg';
            Product::create($row);
        }
    }
}
